// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using X_Technology_ORTv2.Models;

namespace X_Technology_ORTv2.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201118225317_SeedDataInitialProducts")]
    partial class SeedDataInitialProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("X_Technology_ORTv2.Models.Billing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Billings");
                });

            modelBuilder.Entity("X_Technology_ORTv2.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.ToTable("OrdersDetails");
                });

            modelBuilder.Entity("X_Technology_ORTv2.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BillingId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShippingId")
                        .HasColumnType("int");

                    b.Property<string>("ShippingMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalPaid")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BillingId");

                    b.HasIndex("ShippingId");

                    b.ToTable("OrdersHeader");
                });

            modelBuilder.Entity("X_Technology_ORTv2.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Samsung",
                            Category = "Sonido",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Ftiendanaranja.com.py%2Ftienda-movil%2F21699-auriculares-samsung-level-on-wireless-pro-bluetooth.html&psig=AOvVaw1FI-87pR0hRpty8iNwB5Gj&ust=1605825463702000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLCDq5WUje0CFQAAAAAdAAAAABAG",
                            Price = 200f,
                            Sku = "1",
                            Title = "Auriculares"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "JBL",
                            Category = "Sonido",
                            ImageUrl = "https://d34zlyc2cp9zm7.cloudfront.net/products/7840b4935124524a1351becd203fc8ff992b1785a1ffaf8287a26aadb90953fc.jpg_1000",
                            Price = 160f,
                            Sku = "3",
                            Title = "Parlante"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "LG",
                            Category = "Entretenimiento",
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_930556-MLA41195666242_032020-V.webp",
                            Price = 350f,
                            Sku = "3",
                            Title = "Television"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Samsung",
                            Category = "Entretenimiento",
                            ImageUrl = "https://i1.wp.com/clipset.com/wp-content/uploads/2016/05/samsung-smart-tv.jpg?fit=916%2C600&ssl=1",
                            Price = 400f,
                            Sku = "1",
                            Title = "Television"
                        });
                });

            modelBuilder.Entity("X_Technology_ORTv2.Models.Shipping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shippings");
                });

            modelBuilder.Entity("X_Technology_ORTv2.Models.OrderDetail", b =>
                {
                    b.HasOne("X_Technology_ORTv2.Models.OrderHeader", null)
                        .WithMany("Details")
                        .HasForeignKey("OrderHeaderId");
                });

            modelBuilder.Entity("X_Technology_ORTv2.Models.OrderHeader", b =>
                {
                    b.HasOne("X_Technology_ORTv2.Models.Billing", "Billing")
                        .WithMany()
                        .HasForeignKey("BillingId");

                    b.HasOne("X_Technology_ORTv2.Models.Shipping", "Shipping")
                        .WithMany()
                        .HasForeignKey("ShippingId");
                });
#pragma warning restore 612, 618
        }
    }
}
