// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using X_Technology_ORTv2.Models;

namespace X_Technology_ORTv2.Migrations
{
    [DbContext(typeof(Context))]
<<<<<<< HEAD:Migrations/20201105013125_initial.Designer.cs
    [Migration("20201105013125_initial")]
    partial class initial
=======
    [Migration("20201112020040_InitialCreate")]
    partial class InitialCreate
>>>>>>> d7d614f7073ef9ac830dbf69a0899e29eba009fd:Migrations/20201112020040_InitialCreate.Designer.cs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("X_Technology_ORTv2.Models.Billing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Billings");
                });

            modelBuilder.Entity("X_Technology_ORTv2.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.ToTable("OrdersDetails");
                });

            modelBuilder.Entity("X_Technology_ORTv2.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BillingId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShippingId")
                        .HasColumnType("int");

                    b.Property<string>("ShippingMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalPaid")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BillingId");

                    b.HasIndex("ShippingId");

                    b.ToTable("OrdersHeader");
                });

            modelBuilder.Entity("X_Technology_ORTv2.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

<<<<<<< HEAD:Migrations/20201105013125_initial.Designer.cs
                    b.Property<int?>("OrderDetailId")
                        .HasColumnType("int");

=======
>>>>>>> d7d614f7073ef9ac830dbf69a0899e29eba009fd:Migrations/20201112020040_InitialCreate.Designer.cs
                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

<<<<<<< HEAD:Migrations/20201105013125_initial.Designer.cs
                    b.HasIndex("OrderDetailId");

=======
>>>>>>> d7d614f7073ef9ac830dbf69a0899e29eba009fd:Migrations/20201112020040_InitialCreate.Designer.cs
                    b.ToTable("Products");
                });

            modelBuilder.Entity("X_Technology_ORTv2.Models.Shipping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shippings");
                });

            modelBuilder.Entity("X_Technology_ORTv2.Models.OrderDetail", b =>
                {
                    b.HasOne("X_Technology_ORTv2.Models.OrderHeader", null)
                        .WithMany("Details")
                        .HasForeignKey("OrderHeaderId");
                });

            modelBuilder.Entity("X_Technology_ORTv2.Models.OrderHeader", b =>
                {
                    b.HasOne("X_Technology_ORTv2.Models.Billing", "Billing")
                        .WithMany()
                        .HasForeignKey("BillingId");

                    b.HasOne("X_Technology_ORTv2.Models.Shipping", "Shipping")
                        .WithMany()
                        .HasForeignKey("ShippingId");
                });
<<<<<<< HEAD:Migrations/20201105013125_initial.Designer.cs

            modelBuilder.Entity("X_Technology_ORTv2.Models.Product", b =>
                {
                    b.HasOne("X_Technology_ORTv2.Models.OrderDetail", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderDetailId");
                });
=======
>>>>>>> d7d614f7073ef9ac830dbf69a0899e29eba009fd:Migrations/20201112020040_InitialCreate.Designer.cs
#pragma warning restore 612, 618
        }
    }
}
